version: "3.9"

services:
  captcha-solver-api:
    container_name: captcha-solver-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      API_PORT: 3000
    restart: unless-stopped
